"""Package the test set + its processed output as a submission deliverable.

The brief asks for "at least 15 diverse base images together with the system's
output". This runs the pipeline over the test set and copies a curated slice of
the artifacts into ``deliverables/sample_run/`` - small enough to live in git,
complete enough to judge:

  * every base:      source, alpha mask, review overlay, sidecar JSON
  * four showcases:  additionally the cut-out, trimap, shadow, highlight and
                     displacement layers, so the bonus track is visible
  * the batch report, the per-image CSV, and the evaluation summary

    python scripts/export_deliverable.py
    python scripts/export_deliverable.py --all-layers     # everything, ~26 MB
"""
from __future__ import annotations

import argparse
import json
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from app.batch import BatchJob, WorkItem, run_batch  # noqa: E402
from app.config import settings  # noqa: E402
from app.imaging import SUPPORTED_EXT  # noqa: E402
from app.pipeline import ProcessOptions  # noqa: E402
from app.report import render_report  # noqa: E402
from app.segmentation import registry  # noqa: E402
from app.storage import JobStore  # noqa: E402

# One per category, chosen to show the range: fabric folds + hair, the
# lowest-contrast boundary, a perspective quad, and a structural hole.
SHOWCASE = ("03_tee_on_model_hair", "04_hoodie_folds", "08_mug_white_on_white",
            "13_canvas_perspective")

ALWAYS = ("_mask.png", "_overlay.jpg", "_meta.json")
EXTRA = ("_cutout.png", "_trimap.png", "_shadow.png", "_highlight.png", "_displacement.png")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--folder", type=Path, default=ROOT / "data" / "samples")
    ap.add_argument("--out", type=Path, default=ROOT / "deliverables" / "sample_run")
    ap.add_argument("--all-layers", action="store_true",
                    help="keep every layer for every image (~26 MB instead of ~9 MB)")
    args = ap.parse_args()

    files = sorted(p for p in args.folder.iterdir()
                   if p.is_file() and p.suffix.lower() in SUPPORTED_EXT)
    if not files:
        print(f"no images in {args.folder}; run scripts/make_dataset.py first")
        return 1

    hints: dict[str, str] = {}
    manifest = args.folder / "manifest.csv"
    if manifest.exists():
        import csv

        with manifest.open(encoding="utf-8-sig") as fh:
            for row in csv.DictReader(fh):
                if row.get("file"):
                    hints[row["file"]] = (row.get("category") or "auto").strip()

    print(f"warming models on {settings.resolved_device()} ...")
    warm = registry.warmup()

    store = JobStore.create("deliv_")
    items = [WorkItem(source=p.name, path=str(p), category=hints.get(p.name, "auto"))
             for p in files]
    job = BatchJob(job_id=store.job_id, total=len(items))
    print(f"processing {len(items)} bases ...")
    results, summary = run_batch(store, items, ProcessOptions(), job=job)
    store.save_text("report.html", render_report(store.job_id, results, summary, meta={
        "model": warm.get("primary"), "cross_check": warm.get("cross_check"),
        "device": settings.resolved_device(), "infer_size": settings.infer_size,
        "source": str(args.folder),
    }), mime="text/html")

    out = args.out
    if out.exists():
        shutil.rmtree(out)
    (out / "sources").mkdir(parents=True, exist_ok=True)
    (out / "output").mkdir(parents=True, exist_ok=True)

    kept = 0
    for res in results:
        src = args.folder / res.source
        if src.exists():
            shutil.copy2(src, out / "sources" / src.name)
        stem = res.id
        wanted = ALWAYS + (EXTRA if (args.all_layers or
                                     any(s in stem for s in SHOWCASE)) else ())
        for suffix in wanted:
            path = store.path_for(f"{stem}{suffix}")
            if path.exists():
                shutil.copy2(path, out / "output" / path.name)
                kept += 1

    for name in ("report.html", "batch_results.csv", "batch_results.json"):
        path = store.path_for(name)
        if path.exists():
            shutil.copy2(path, out / name)

    eval_summary = ROOT / "data" / "eval" / "eval_summary.json"
    if eval_summary.exists():
        shutil.copy2(eval_summary, out / "eval_summary.json")
    bench = ROOT / "data" / "eval" / "bench.json"
    if bench.exists():
        shutil.copy2(bench, out / "bench.json")

    readme = out / "README.md"
    readme.write_text(f"""# Test set + system output

Generated by `python scripts/export_deliverable.py`.

* `sources/` - the {len(files)} test bases (rendered by `scripts/make_dataset.py`,
  deterministic, no third-party imagery). Ground truth alphas live in
  `data/samples/ground_truth/`.
* `output/` - what the pipeline produced. Every base has `*_mask.png` (the
  deliverable alpha mask, at the source resolution), `*_overlay.jpg` (review
  view) and `*_meta.json` (full QC breakdown, print-area geometry, timings).
  These four bases additionally carry every bonus layer - cut-out, trimap,
  shadow, highlight, displacement: {', '.join(SHOWCASE)}.
* `report.html` - the batch automation report (open it directly; artifact paths
  are relative). Point it at `output/` if you move files around.
* `batch_results.csv` / `.json` - one row per base for the ops team.
* `eval_summary.json` - IoU / boundary-F1 / routing quality against ground truth.
* `bench.json` - latency and throughput measurements.

## Result summary for this run

| | |
|---|---|
| Bases processed | {summary.total} |
| READY (auto-published) | {summary.ready} ({summary.automation_rate * 100:.1f}%) |
| REVIEW (to a designer) | {summary.review} |
| FAILED | {summary.failed} |
| Mean confidence | {summary.mean_confidence:.3f} |
| Mean latency | {summary.mean_latency_ms:.0f} ms |
| Throughput | {summary.throughput_img_per_min:.1f} images/min |
| Model | {warm.get('primary')} + {warm.get('cross_check')} cross-check on {settings.resolved_device()} |
""", encoding="utf-8")

    size_mb = sum(p.stat().st_size for p in out.rglob("*") if p.is_file()) / 1e6
    print(f"\n{kept} artifacts + {len(files)} sources -> {out}  ({size_mb:.1f} MB)")
    print(f"automation rate {summary.automation_rate * 100:.1f}%  "
          f"({summary.ready} READY / {summary.review} REVIEW / {summary.failed} FAILED)")
    print(json.dumps(summary.model_dump(), indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
